/**
 * War With A Mate — episode links from the public RSS feed (rss.com).
 * Regenerate: download https://media.rss.com/war-with-a-mate/feed.xml to prisma/_wwam_feed.xml,
 * then `node prisma/scripts/extractWwamEpisodes.mjs`.
 */
export type WwamRssEpisode = {
  episodeIndex: number;
  url: string;
  title: string;
  itunesEpisode: string | null;
};

export const WWAM_RSS_EPISODES: readonly WwamRssEpisode[] = [
  { episodeIndex: 1, url: "https://rss.com/podcasts/war-with-a-mate/1841305", title: "Episode 1 : Making A Meal Out Of It", itunesEpisode: "1" },
  { episodeIndex: 2, url: "https://rss.com/podcasts/war-with-a-mate/1841311", title: "Episode 2 : Camel Lot", itunesEpisode: "2" },
  { episodeIndex: 3, url: "https://rss.com/podcasts/war-with-a-mate/1852496", title: "Episode 5 - Subtle, Humble, Brave", itunesEpisode: "5" },
  { episodeIndex: 4, url: "https://rss.com/podcasts/war-with-a-mate/1852489", title: "Episode 4 - Pyramid Scheme", itunesEpisode: "4" },
  { episodeIndex: 5, url: "https://rss.com/podcasts/war-with-a-mate/1852485", title: "Episode 3 - History (w/Echoes of War)", itunesEpisode: "3" },
  { episodeIndex: 6, url: "https://rss.com/podcasts/war-with-a-mate/1862984", title: "Episode 6: Bin Weevils", itunesEpisode: "6" },
  { episodeIndex: 7, url: "https://rss.com/podcasts/war-with-a-mate/1863094", title: "Episode 7: Michael McIntyre", itunesEpisode: "7" },
  { episodeIndex: 8, url: "https://rss.com/podcasts/war-with-a-mate/1863120", title: "Episode 8: Sleepwalking", itunesEpisode: "8" },
  { episodeIndex: 9, url: "https://rss.com/podcasts/war-with-a-mate/1874595", title: "Episode 9: The Vow", itunesEpisode: "9" },
  { episodeIndex: 10, url: "https://rss.com/podcasts/war-with-a-mate/1885472", title: "Episode 10: Click", itunesEpisode: "10" },
  { episodeIndex: 11, url: "https://rss.com/podcasts/war-with-a-mate/1897669", title: "Episode 11: Uncle Climax", itunesEpisode: "11" },
  { episodeIndex: 12, url: "https://rss.com/podcasts/war-with-a-mate/1908176", title: "Ep 12: Everest", itunesEpisode: "12" },
  { episodeIndex: 13, url: "https://rss.com/podcasts/war-with-a-mate/1918343", title: "Episode 13: The Way Old Back Times", itunesEpisode: "13" },
  { episodeIndex: 14, url: "https://rss.com/podcasts/war-with-a-mate/1930255", title: "Episode 14: The Haunted Mansion", itunesEpisode: "14" },
  { episodeIndex: 15, url: "https://rss.com/podcasts/war-with-a-mate/1940040", title: "Episode 15: Digging In", itunesEpisode: "15" },
  { episodeIndex: 16, url: "https://rss.com/podcasts/war-with-a-mate/1951764", title: "Episode 16: Mean, Green, Hungry Regime", itunesEpisode: "16" },
  { episodeIndex: 17, url: "https://rss.com/podcasts/war-with-a-mate/1961864", title: "Episode 17: Pasta Point Of No Return", itunesEpisode: "17" },
  { episodeIndex: 18, url: "https://rss.com/podcasts/war-with-a-mate/1972617", title: "Episode 18: The Super-Naturals", itunesEpisode: "18" },
  { episodeIndex: 19, url: "https://rss.com/podcasts/war-with-a-mate/1982503", title: "Ep 19: High-Energy Podcast Adventure", itunesEpisode: "19" },
  { episodeIndex: 20, url: "https://rss.com/podcasts/war-with-a-mate/1992344", title: "Episode 20: Cyphers, Sand And A Tranquil Land", itunesEpisode: "20" },
  { episodeIndex: 21, url: "https://rss.com/podcasts/war-with-a-mate/2001421", title: "Episode 21: First Blood", itunesEpisode: "21" },
  { episodeIndex: 22, url: "https://rss.com/podcasts/war-with-a-mate/2011743", title: "Episode 22: All Men Are On Islands", itunesEpisode: "22" },
  { episodeIndex: 23, url: "https://rss.com/podcasts/war-with-a-mate/2021225", title: "Episode 23: Sisyphus", itunesEpisode: "23" },
  { episodeIndex: 24, url: "https://rss.com/podcasts/war-with-a-mate/2032178", title: "Episode 24: Graziani’s Defensive", itunesEpisode: "24" },
  { episodeIndex: 25, url: "https://rss.com/podcasts/war-with-a-mate/2041650", title: "Episode 25: The Rat Pack (w/KamSandwich)", itunesEpisode: "25" },
  { episodeIndex: 26, url: "https://rss.com/podcasts/war-with-a-mate/2052109", title: "Episode 26: The Trucks", itunesEpisode: "26" },
  { episodeIndex: 27, url: "https://rss.com/podcasts/war-with-a-mate/2061962", title: "Episode 27: If It Bleeds, We Can Kill It", itunesEpisode: "27" },
  { episodeIndex: 28, url: "https://rss.com/podcasts/war-with-a-mate/2072378", title: "Episode 28: Airing It Out", itunesEpisode: "28" },
  { episodeIndex: 29, url: "https://rss.com/podcasts/war-with-a-mate/2082674", title: "Episode 29: The Dogfight At Mersa Matruh", itunesEpisode: "29" },
  { episodeIndex: 30, url: "https://rss.com/podcasts/war-with-a-mate/2091686", title: "Episode 30: The War Room, Part 1", itunesEpisode: "30" },
  { episodeIndex: 31, url: "https://rss.com/podcasts/war-with-a-mate/2098443", title: "Episode 31: Who Did This?", itunesEpisode: "31" },
  { episodeIndex: 32, url: "https://rss.com/podcasts/war-with-a-mate/2110610", title: "Episode 32: Fixed Bayonets", itunesEpisode: "32" },
  { episodeIndex: 33, url: "https://rss.com/podcasts/war-with-a-mate/2119798", title: "Episode 33: “It Was A Good Day”", itunesEpisode: "33" },
  { episodeIndex: 34, url: "https://rss.com/podcasts/war-with-a-mate/2136944", title: "Episode 34: Trains, Planes and Automobiles", itunesEpisode: "34" },
  { episodeIndex: 35, url: "https://rss.com/podcasts/war-with-a-mate/2148466", title: "Episode 35: Free Fallin’", itunesEpisode: "35" },
  { episodeIndex: 36, url: "https://rss.com/podcasts/war-with-a-mate/2157929", title: "Episode 36: Doom", itunesEpisode: "36" },
  { episodeIndex: 37, url: "https://rss.com/podcasts/war-with-a-mate/2166743", title: "Episode 37: On The Turn", itunesEpisode: "37" },
  { episodeIndex: 38, url: "https://rss.com/podcasts/war-with-a-mate/2178327", title: "Episode 38: May You Fight Long And Well (w/Breakup Gaming Society)", itunesEpisode: "38" },
  { episodeIndex: 39, url: "https://rss.com/podcasts/war-with-a-mate/2189797", title: "Episode 39: Gastronauts", itunesEpisode: "39" },
  { episodeIndex: 40, url: "https://rss.com/podcasts/war-with-a-mate/2201011", title: "Episode 40: Ragebait", itunesEpisode: "40" },
  { episodeIndex: 41, url: "https://rss.com/podcasts/war-with-a-mate/2212028", title: "Episode 41: The Unreserved", itunesEpisode: "41" },
  { episodeIndex: 42, url: "https://rss.com/podcasts/war-with-a-mate/2223604", title: "Episode 42: Fire Hazards", itunesEpisode: "42" },
  { episodeIndex: 43, url: "https://rss.com/podcasts/war-with-a-mate/2238951", title: "Episode 43: Plain Sailing", itunesEpisode: "43" },
  { episodeIndex: 44, url: "https://rss.com/podcasts/war-with-a-mate/2251037", title: "Episode 44: Icarus", itunesEpisode: "44" },
  { episodeIndex: 45, url: "https://rss.com/podcasts/war-with-a-mate/2264657", title: "Episode 45: Dog Days", itunesEpisode: "45" },
  { episodeIndex: 46, url: "https://rss.com/podcasts/war-with-a-mate/2278340", title: "Episode 46: Ships In The Night", itunesEpisode: null },
  { episodeIndex: 47, url: "https://rss.com/podcasts/war-with-a-mate/2278421", title: "Episode 46: Ships In The Night", itunesEpisode: "46" },
  { episodeIndex: 48, url: "https://rss.com/podcasts/war-with-a-mate/2289273", title: "Episode 47: Alternate Routes", itunesEpisode: "47" },
  { episodeIndex: 49, url: "https://rss.com/podcasts/war-with-a-mate/2301817", title: "Episode 48: The Spooktacular", itunesEpisode: "48" },
  { episodeIndex: 50, url: "https://rss.com/podcasts/war-with-a-mate/2316366", title: "Episode 49: The Best Medicine", itunesEpisode: "49" },
  { episodeIndex: 51, url: "https://rss.com/podcasts/war-with-a-mate/2327808", title: "Episode 50: Anniversary", itunesEpisode: "50" },
  { episodeIndex: 52, url: "https://rss.com/podcasts/war-with-a-mate/2340794", title: "Episode 51: The Sandstorm", itunesEpisode: "51" },
  { episodeIndex: 53, url: "https://rss.com/podcasts/war-with-a-mate/2356240", title: "Episode 52: Happy-Go-Lucky Scamp", itunesEpisode: "52" },
  { episodeIndex: 54, url: "https://rss.com/podcasts/war-with-a-mate/2370796", title: "Episode 53: I Want To Believe", itunesEpisode: "53" },
  { episodeIndex: 55, url: "https://rss.com/podcasts/war-with-a-mate/2388889", title: "Episode 54: Tomorrow Never Comes", itunesEpisode: "54" },
  { episodeIndex: 56, url: "https://rss.com/podcasts/war-with-a-mate/2401786", title: "Episode 55: Tomorrow Came", itunesEpisode: "55" },
  { episodeIndex: 57, url: "https://rss.com/podcasts/war-with-a-mate/2414538", title: "Episode 56: Matemas", itunesEpisode: "56" },
  { episodeIndex: 58, url: "https://rss.com/podcasts/war-with-a-mate/2426744", title: "Episode 57: The Camel Conclusion", itunesEpisode: "57" },
  { episodeIndex: 59, url: "https://rss.com/podcasts/war-with-a-mate/2452313", title: "Episode 58: The Grapes of Ghent", itunesEpisode: "58" },
  { episodeIndex: 60, url: "https://rss.com/podcasts/war-with-a-mate/2464848", title: "Episode 59: Writing On The Wall", itunesEpisode: "59" },
  { episodeIndex: 61, url: "https://rss.com/podcasts/war-with-a-mate/2479381", title: "Episode 60: Deserts Of Our Minds", itunesEpisode: "60" },
  { episodeIndex: 62, url: "https://rss.com/podcasts/war-with-a-mate/2508995", title: "Episode 61: Andy & James’ Day Off", itunesEpisode: "61" },
  { episodeIndex: 63, url: "https://rss.com/podcasts/war-with-a-mate/2530185", title: "Episode 62: The Other Type Of Luck", itunesEpisode: "62" },
  { episodeIndex: 64, url: "https://rss.com/podcasts/war-with-a-mate/2547410", title: "Episode 63: Humbled", itunesEpisode: "63" },
  { episodeIndex: 65, url: "https://rss.com/podcasts/war-with-a-mate/2566396", title: "Episode 63.5: Technical Difficulties", itunesEpisode: null },
  { episodeIndex: 66, url: "https://rss.com/podcasts/war-with-a-mate/2585616", title: "Episode 64: F.I.A.H.F.T.F.D", itunesEpisode: "64" },
  { episodeIndex: 67, url: "https://rss.com/podcasts/war-with-a-mate/2587878", title: "Episode 65: Dungeon & Drag-On", itunesEpisode: "65" },
  { episodeIndex: 68, url: "https://rss.com/podcasts/war-with-a-mate/2605456", title: "Episode 66: Genuinely Awful Stuff & Sardonic Art", itunesEpisode: "66" },
  { episodeIndex: 69, url: "https://rss.com/podcasts/war-with-a-mate/2625464", title: "Episode 67: I Don’t Understand The Joke Well Enough To Make It", itunesEpisode: "67" },
  { episodeIndex: 70, url: "https://rss.com/podcasts/war-with-a-mate/2646266", title: "Episode 68: How I Met Our Mother", itunesEpisode: "68" },
  { episodeIndex: 71, url: "https://rss.com/podcasts/war-with-a-mate/2669344", title: "Episode 69: Coming Together", itunesEpisode: "69" },
] as const;
